---
env:
  FULL_TAG: "${{ github.repository_owner }}/${{ github.repository }}:latest"
  IMAGE_NAME: "${{ github.repository }}"
  REGISTRY: ghcr.io
  TEST_TAG: "${{ github.repository_owner }}/${{ github.repository }}:test"
jobs:
  build:
    permissions:
      contents: read
      id-token: write
      packages: write
    runs-on: ubuntu-latest
  steps:
    -
      name: "Checkout repository"
      uses: actions/checkout@v2
      with:
        submodules: recursive
    -
      id: meta
      name: "Extract Docker metadata"
      uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
      with:
        images: "${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}"
    -
      name: "Login to GitHub Container Registry"
      uses: docker/login-action@v1
      with:
        password: "${{ secrets.GITHUB_TOKEN }}"
        registry: ghcr.io
        username: "${{ github.repository_owner }}"
    -
      name: "Login to DockerHub"
      uses: docker/login-action@v1
      with:
        password: "${{ secrets.DOCKERHUB_TOKEN }}"
        username: "${{ secrets.DOCKERHUB_USERNAME }}"
    -
      name: "Build and export to Docker"
      uses: docker/build-push-action@v2
      with:
        context: "."
        load: true
        tags: "${{ env.TEST_TAG }}"
    -
      name: "Run the Anchore scan action itself with GitHub Advanced Security code scanning integration enabled"
      uses: anchore/scan-action@b08527d5ae7f7dc76f9621edb6e49eaf47933ccd
      with:
        acs-report-enable: true
        image: "${{ env.TEST_TAG }}"
    -
      name: "Upload Anchore Scan Report"
      uses: github/codeql-action/upload-sarif@v1
      with:
        sarif_file: results.sarif
    -
      name: "Run Trivy vulnerability scanner"
      uses: aquasecurity/trivy-action@2a2157eb22c08c9a1fac99263430307b8d1bc7a2
      with:
        format: template
        image-ref: "${{ env.TEST_TAG }}"
        output: trivy-results.sarif
        severity: "CRITICAL,HIGH"
        template: "@/contrib/sarif.tpl"
    -
      name: "Upload Trivy scan results to GitHub Security tab"
      uses: github/codeql-action/upload-sarif@v1
      with:
        sarif_file: trivy-results.sarif
    -
      id: build-and-push
      name: "Build and push Docker image"
      uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
      with:
        context: "."
        labels: "${{ steps.meta.outputs.labels }}"
        platforms: "linux/amd64,linux/arm64"
        push: "${{ github.event_name != 'pull_request' }}"
        tags: "${{ env.FULL_TAG }}"
    -
      env:
        COSIGN_EXPERIMENTAL: "true"
        run: "cosign sign ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}@${{ steps.build-and-push.outputs.digest }}"
      if: "${{ github.event_name != 'pull_request' }}"
      name: "Sign the published Docker image"
name: Docker
true:
  push:
    branches:
      - main
    tags:
      - v*.*.*
